# Generated by Django 4.1.1 on 2022-09-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreCli', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=40, null=True, verbose_name='Direccion')),
            ],
        ),
    ]
