# Generated by Django 4.1.1 on 2022-09-26 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Id_Producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_prod', models.CharField(max_length=100, verbose_name='Nombre_Producto')),
                ('precio_prod', models.CharField(max_length=100, verbose_name='Precio_Producto')),
                ('Contenido_neto', models.CharField(max_length=15, verbose_name='Contenido_neto')),
                ('Descripcion_prod', models.CharField(max_length=200, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('Id_Servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_Ser', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio_Ser', models.CharField(max_length=40, verbose_name='Precio')),
                ('descripcion_Ser', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('Id_venta', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='esteticApp.productos')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='esteticApp.servicios')),
            ],
        ),
    ]
