# Generated by Django 4.1.1 on 2022-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_Servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_Ser', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio_Ser', models.CharField(max_length=100, verbose_name='Precio')),
                ('descripcion_Ser', models.CharField(max_length=15, verbose_name='Descripción')),
            ],
        ),
    ]
