# Generated by Django 4.1.1 on 2022-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Id_Producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_prod', models.CharField(max_length=100, verbose_name='Nombre_Producto')),
                ('precio_prod', models.CharField(max_length=100, verbose_name='Precio_Producto')),
                ('Contenido_neto', models.CharField(max_length=15, verbose_name='Contenido_neto')),
                ('Descripcion_prod', models.CharField(max_length=40, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
