# Generated by Django 4.1.1 on 2022-09-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteticApp', '0002_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion_Ser',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre_Ser',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio_Ser',
            field=models.CharField(max_length=40, verbose_name='Precio'),
        ),
    ]
